sonar.projectKey=cc-symfony
sonar.projectName=CC Symfony


sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage.xml

# Ignorer les dépendances et les fichiers générés
sonar.exclusions=vendor/**,var/**,public/build/**
